### ISSUE TITLE
Multiple modules accessing SDRAM

### ISSUE THREAD

**Issue by milanvidakovic** [stffrdhrn/sdram-controller#2]
Hi,
Thanks for the great example. I was able to run your SDRAM controller demo from the Quartus II successfully. However, when I tried to modify your example, I ran into problems. 

First of all, could you tell me what am I doing wrong? Here is the code:
I write to the SDRAM this way;

initial begin

	mpc <= 0;
	phase <= 0;
	rd_ack_r <= 1;
	mem_busy_r <= 0;
	cnt <= 0;

	text[0] <= "H";
	text[1] <= "e";
	text[2] <= "l";
	text[3] <= "l";
	text[4] <= "o";
end

always @ (posedge clk) begin

	if (cnt <= 999999) begin
		cnt <= cnt + 1;
	end
	else begin
		cnt <= 0;
		case (phase) 
			0: begin
				mem_busy_r <= 1;
				
				rd_data_r <= mpc;
				addr <= mpc;
				rd_enable_r <= 0;
				wr_enable_r <= 1;
				wr_data_r <= text[mpc];
				if (mpc < 4) begin
					mpc <= mpc + 1;
					phase <= 0;
				end
				else begin
					mpc <= 0;
					phase <= 1;
					mem_busy_r <= 0;
				end
			end
		endcase
	end
end

This code works properly, and writes the "Hello" string into the memory. However, when I try to read it, I have problems:

always @ (posedge clk) begin

	if (cnt <= 999999) begin
		cnt <= cnt + 1;
	end
	else begin
		cnt <= 0;
		case (phase) 
			1: begin
				mem_busy_r <= 1;
				rd_ack_r <= 1;
				addr <= mpc;
				rd_enable_r <= 1;
				wr_enable_r <= 0;
				phase <= 2;
				end
			2: begin
			   rd_ack_r <= 0;
				//if (rd_rdy) begin
					rd_data_r <= rd_data;
					if (mpc < 4) begin
						mpc <= mpc + 1;
						phase <= 1;
					end
					else begin
						mpc <= 0;
						phase <= 4;
					end
				//end
				/*else begin
					rd_data_r <= 0;
	  				phase <= 1;
				end*/
				mem_busy_r <= 0;
			end
		endcase
	end
end
`
I had to comment out the rd_rdy checkup to make it read. What am I doing wrong?

Also, when I introduced the other module to read the same memory, it would not read anything more than the last entry (the letter 'o'). 

I am a beginner in this field and I am working from the scratch. Nios examples are far too complicated for me.

Best regards,
Milan

**Comment by stffrdhrn** [comment]
Hello,

Thanks for using my sdram core.

Why are you doing  writes to these input registers?  In the read portion.

```
			mem_busy_r <= 1;
			
			rd_data_r <= mpc;
```

Also, I think you are missing the logic to wait for the `busy` signals to ack the write before incrementing your mpc.   This controller has no buffering so you will need to watch for the busy signal before sending any new read/write operations.

Also, if you have multiple masters reading and writing to memory you will need some kind of bus arbiter to grant access to the bus.  I don't have an implementation of one, but you can look at the wishbone bus arbiter. 

i.e. section 10.5 https://cdn.opencores.org/downloads/wbspec_b3.pdf

**Comment by milanvidakovic** [comment]
Hi,
thanks for the reply!

I have wired the rd_data_r to the LEDs on the de0-nano, so I could read the address I am writing into (mpc). I have done that "rd_data_r <= mpc;" in the write phase of the code, and If you think that I should remove it, I will do it.
 
What is confusing me is that I have tried to recycle your code and I have replaced your dnano_interface module with my module in which I am not pressing the buttons; instead, I use the counter first to write into the SDRAM, and then to read from it. Could you confirm, or correct my interpretation of your SDRAM controller operations?

Here is how I understand it:
# 1. Write operations.
To make a write into the SDRAM, I should do the following:
				addr <= **<address_to_write>**;
				rd_enable_r <= 0;
				wr_enable_r <= 1;
				wr_data_r <= **<data_to_write>**;

I use the same names as in your dnano_interface module, and the corresponding wiring:

module read_write_mem (
  input clk,
  input button_n,
  output wire [7:0] leds,

  /* Controller Interface */
  output  [23:0] haddr,      // RW-FIFO- data1
  input          busy,       // RW-FIFO- full
  output         wr_enable,  // WR-FIFO- write
  output [15:0]  wr_data,    // WR-FIFO- data2
  output         rd_enable,  // RO-FIFO- write
  input   [15:0] rd_data,    // RI-FIFO- data
  input          rd_rdy,     // RI-FIFO-~empty
  output         rd_ack     // RI-FIFO- read
);
assign wr_data = wr_data_r;
assign haddr = addr;
assign rd_ack = rd_ack_r;
assign leds = rd_data_r[7:0];
assign mem_busy = mem_busy_r;

assign rd_enable = rd_enable_r ;
assign wr_enable = wr_enable_r ;

# 2. Read operations
To read from the SDRAM, I should do the following:
   rd_enable_r <= 1;
   rd_ack_r <= rd_rdy;
   
   if (rd_rdy)
     rd_data_r <= rd_data;
   else 
     rd_data_r <= rd_data_r;

This code above doesn't work for me. If I leave it like that, I cannot read anything. If I comment out the if(rd_rdy) line, then I am able to read.

I am looking at your example in the dnano_interface module and I cannot figure out what exactly should I do. I also don't understand where I should check the busy signal, since the only place where I see it is here:
assign dbl_clck_rst_n = rst_n & ~busy;

Thanks in advance,
Milan

**Comment by stffrdhrn** [comment]
Hello, sorry for the extremely late reply I didn't see this.  Please re-ping if I don't reply for a while.

The issue with using my `dnano_interface` directly is that it works with dual clock fifo's not with the actual sdram controller.  A previous version worked directly with the [sdram controller directly](https://github.com/stffrdhrn/sdram-controller/blob/17be7a0419f160c665c66f37fa41f84520c45876/rtl/dnano_interface.v).

```
module read_write_mem (
  input clk,
  input button_n,
  output wire [7:0] leds,

  /* Controller Interface */
  output [23:0] haddr, // RW-FIFO- data1
  input busy, // RW-FIFO- full
  output wr_enable, // WR-FIFO- write
  output [15:0] wr_data, // WR-FIFO- data2
  output rd_enable, // RO-FIFO- write
  input [15:0] rd_data, // RI-FIFO- data
  input rd_rdy,                                          // RI-FIFO-~empty << from fifo
  output rd_ack                                       // RI-FIFO- read
);

assign wr_data = wr_data_r;
assign haddr = addr;
assign rd_ack = rd_ack_r;
assign leds = rd_data_r[7:0];
assign mem_busy = mem_busy_r;

assign rd_enable = rd_enable_r ;
assign wr_enable = wr_enable_r ;
```

I think there is an issue with you using rd_rdy and rd_ack (which is supposed to be connected to a fifo.) 
Without fifo's rd_ready should be connected to the sdram controller and you should not need a rd_ack signal.   Above your comments say FIFO, are you using it?

In order to read from the controller you just need to do:

```
assign rd_addr <= "incoming address"; 
// Send rd_enabled to SDRAM on read request
always @ (posedge clock)
  if (read requested from button push)
     begin
        rd_enable_r <= 1;
        wr_enable_r <= 0;
     end

// Wait for read ready from sdram, it will come some time later
always @ (posedge clock)
if (rd_rdy)
  rd_data_r <= rd_data;
else
  rd_data_r <= rd_data_r;
```

or with thinking of the busy signal.

```
if (~busy)
  begin
   rd_enable_r <= 1;
   wr_enable_r <= 0;
  end

if (~busy & rd_ready)
  rd_data_r <= rd_data;
```

**Comment by milanvidakovic** [comment]
Hi, thanks for the reply! You are right - I misunderstood your example. I was able to figure it out and now I have a working [FPGA DE0-NANO-based 32-bit computer](https://github.com/milanvidakovic/FPGAComputer32) that uses your sdram controller to access the 32MB of SDRAM on the board. Thanks for the code!

**Comment by stffrdhrn** [comment]
Good to hear it's working. I should add a more simple example.
