### ISSUE TITLE
CPLD latch output issues

### ISSUE THREAD

**Issue by briansune** [stffrdhrn/sdram-controller#5]
Just wonder, if using FPGA the modified example code from your repository seems dont have big issues due to most FPGA do have output buffer register to control the timing.

However, if considering the case of CPLD devices, most of them dont even able to have output IO register buffer to control the clock alignment.

So after some testings and findings, i discovered that CPLD device have unnecessary switching noise at the output due to some signal paths only use latches and MUXx.

Correct me if i think in the wrong direction =]

**Comment by stffrdhrn** [comment]
This might be true. U have not heard of anyone trying on cpld devices.  You should be able to patch all outputs to be registered if that is needed.

**Comment by shubhamnrt** [comment]
hello sir,
i have tried to run your code, what is sdc file in it ?
how to do this ?
create_clock -period "20ns" CLOCK_50
derive_pll_clocks
derive_clock_uncertainty

**Comment by briansune** [comment]
Dear shubhamnrt open a new issues as this is not related to my original question. I am closing this issues as the creator had answered my issues.
Bests~
